version: "3.8"

services:
  postgres:
    image: postgres:12.4
    container_name: mycontacts
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/backup:/backup
    networks:
      - mycontacts
    environment:
      - POSTGRES_DB=mycontacts
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

networks:
  mycontacts:
    driver: bridge
